from typing import Any, Protocol

from .models import VisitCreateCommand, VisitUpdateCommand


VisitRecord = dict[str, Any]


class VisitRepository(Protocol):
    def list(self, user_id: str, query: str = "") -> list[VisitRecord]: ...

    def count_scheduled_on(self, visit_date: str) -> int: ...

    def create(self, command: VisitCreateCommand) -> VisitRecord: ...

    def get(self, visit_id: int) -> VisitRecord | None: ...

    def update(self, visit_id: int, command: VisitUpdateCommand) -> VisitRecord: ...

    def cancel(self, visit_id: int) -> None: ...

    def summarize(self, user_id: str) -> VisitRecord: ...
